vocab = {
    "food": {
        "apple": "äpple",
        "banana": "banan",
        "orange": "apelsin",
        "grape": "druva",
        "pear": "päron",
        "strawberry": "jordgubbe",
        "blueberry": "blåbär",
        "raspberry": "hallon",
        "blackberry": "björnbär",
        "pineapple": "ananas",
        "peach": "persika",
        "watermelon": "vattenmelon",
        "melon": "melon",
        "lemon": "citron",
        "lime": "lime",
        "kiwi": "kiwi",
        "plum": "plommon",
        "cherry": "körsbär",
        "mango": "mango",
        "avocado": "avokado",
        "carrot": "morot",
        "potato": "potatis",
        "tomato": "tomat",
        "cucumber": "gurka",
        "lettuce": "sallad",
        "spinach": "spenat",
        "onion": "lök",
        "garlic": "vitlök",
        "pepper": "paprika",
        "mushroom": "svamp",
        "broccoli": "broccoli",
        "cauliflower": "blomkål",
        "cabbage": "kål",
        "corn": "majs",
        "peas": "ärtor",
        "beans": "bönor",
        "lentils": "linser",
        "rice": "ris",
        "pasta": "pasta",
        "bread": "bröd",
        "butter": "smör",
        "milk": "mjölk",
        "cheese": "ost",
        "cream": "grädde",
        "yogurt": "yoghurt",
        "egg": "ägg",
        "beef": "nötkött",
        "pork": "fläskkött",
        "chicken": "kyckling",
        "fish": "fisk",
        "salmon": "lax",
        "tuna": "tonfisk",
        "shrimp": "räka",
        "lobster": "hummer",
        "crab": "krabba",
        "octopus": "bläckfisk",
        "squid": "bläckfisk",
        "oil": "olja",
        "sugar": "socker",
        "salt": "salt",
        "pepper": "peppar",
        "vinegar": "vinäger",
        "mustard": "senap",
        "ketchup": "ketchup",
        "mayonnaise": "majonnäs",
        "soup": "soppa",
        "salad": "sallad",
        "sandwich": "smörgås",
        "hamburger": "hamburgare",
        "pizza": "pizza",
        "hot dog": "korv",
        "cake": "kaka",
        "cookie": "kaka",
        "ice cream": "glass",
        "chocolate": "choklad",
        "candy": "godis",
        "jam": "sylt",
        "honey": "honung",
        "juice": "juice",
        "tea": "te",
        "coffee": "kaffe",
        "wine": "vin",
        "beer": "öl",
        "water": "vatten",
        "soda": "läsk",
        "whiskey": "whisky",
        "champagne": "champagne",
        "almond": "mandel",
        "cashew": "cashewnöt",
        "hazelnut": "hasselnöt",
        "walnut": "valnöt",
        "pistachio": "pistagenöt",
        "peanut": "jordnöt",
        "basil": "basilika",
        "parsley": "persilja",
        "thyme": "timjan",
        "rosemary": "rosmarin",
        "oregano": "oregano",
        "cinnamon": "kanel",
        "clove": "kryddnejlika",
        "ginger": "ingefära",
        "turmeric": "gurkmeja",
        "coriander": "koriander",
    },
    "colors": {
        "red": "röd",
        "blue": "blå",
        "green": "grön",
        "yellow": "gul",
        "black": "svart",
        "white": "vit",
        "pink": "rosa",
        "purple": "lila",
        "orange": "orange",
        "brown": "brun",
        "gray": "grå",
        "beige": "beige",
        "gold": "guld",
        "silver": "silver",
        "turquoise": "turkos",
        "teal": "teal",
        "navy": "marinblå",
        "maroon": "vinröd",
        "lavender": "lavendel",
        "peach": "persikofärgad",
        
    },
    "common phrases": {
        "hello": "hej",
        "good morning": "god morgon",
        "good afternoon": "god eftermiddag",
        "good evening": "god kväll",
        "good night": "god natt",
        "how are you?": "hur mår du?",
        "I'm fine, thank you": "jag mår bra, tack",
        "what is your name?": "vad heter du?",
        "my name is...": "jag heter...",
        "nice to meet you": "trevligt att träffas",
        "please": "snälla",
        "thank you": "tack",
        "you're welcome": "varsågod",
        "excuse me": "ursäkta mig",
        "sorry": "förlåt",
        "yes": "ja",
        "no": "nej",
        "goodbye": "hejdå",
        "see you later": "vi ses senare",
        "do you speak English?": "talar du engelska?",
        "I don't understand": "jag förstår inte",
        "can you help me?": "kan du hjälpa mig?",
        "how much is this?": "hur mycket kostar detta?",
        "where is the bathroom?": "var är toaletten?",
        "where is the train station?": "var ligger tågstationen?",
        "where is the airport?": "var är flygplatsen?",
        "I'm lost": "jag har gått vilse",
        "what time is it?": "vad är klockan?",
        "I would like...": "jag skulle vilja ha...",
        "can I have the bill, please?": "kan jag få notan, tack?",
        "water": "vatten",
        "coffee": "kaffe",
        "tea": "te",
        "beer": "öl",
        "wine": "vin",
        "breakfast": "frukost",
        "lunch": "lunch",
        "dinner": "middag",
        "do you have...?": "har du...?",
        "I like it": "jag gillar det",
        "I don't like it": "jag gillar det inte",
        "what's your favorite food?": "vad är din favoritmat?",
        "I'm hungry": "jag är hungrig",
        "I'm thirsty": "jag är törstig",
        "can I help you?": "kan jag hjälpa dig?",
        "where do you live?": "var bor du?",
        "I live in...": "jag bor i...",
        "what's your job?": "vad arbetar du med?",
        "I work as...": "jag arbetar som...",
        "how old are you?": "hur gammal är du?",
        "I'm ... years old": "jag är ... år gammal",
        "do you have siblings?": "har du syskon?",
        "I have a brother": "jag har en bror",
        "I have a sister": "jag har en syster",
        "I don't have siblings": "jag har inga syskon",
        "what's the weather like?": "hur är vädret?",
        "it's sunny": "det är soligt",
        "it's raining": "det regnar",
        "it's snowing": "det snöar",
        "it's cloudy": "det är molnigt",
        "it's windy": "det blåser",
        "it's cold": "det är kallt",
        "it's warm": "det är varmt",
        "it's hot": "det är hett",
        "what's your phone number?": "vad är ditt telefonnummer?",
        "where are you from?": "var kommer du ifrån?",
        "I'm from...": "jag kommer från...",
        "do you like it here?": "gillar du det här?",
        "how long have you been here?": "hur länge har du varit här?",
        "can I take a photo?": "kan jag ta en bild?",
        "do you have a pet?": "har du ett husdjur?",
        "do you like sports?": "gillar du sport?",
        "what's your hobby?": "vad är din hobby?",
        "do you have children?": "har du barn?",
        "where do you work?": "var arbetar du?",
        "how's your family?": "hur mår din familj?",
        "what's your address?": "vad är din adress?",
        "do you live alone?": "bor du ensam?",
        "what's your favorite movie?": "vilken är din favoritfilm?",
        "do you like music?": "gillar du musik?",
        "can you repeat that?": "kan du upprepa det?",
        "can I get directions to...?": "kan jag få en vägbeskrivning till...?",
        "I'm tired": "jag är trött",
        "I'm happy": "jag är glad",
        "I'm sad": "jag är ledsen",
        "I'm bored": "jag är uttråkad",
        "I'm excited": "jag är exalterad",
        "I'm nervous": "jag är nervös",
        "I'm scared": "jag är rädd",
        "that's interesting": "det är intressant",
        "I don't know": "jag vet inte",
        "I agree": "jag håller med",
        "I disagree": "jag håller inte med",
        "that's funny": "det är roligt",
        "that's amazing": "det är fantastiskt",
        "I'm sorry to hear that": "jag är ledsen att höra det",
        "I hope so": "jag hoppas det",
        "do you want to go out?": "vill du gå ut?",
        "let's go!": "låt oss gå!",
        "when is your birthday?": "när är din födelsedag?",
        "congratulations!": "grattis!",
        "good luck!": "lycka till!",
        "happy birthday!": "grattis på födelsedagen!",
        "have a nice day!": "ha en bra dag!",
        "take care": "ta hand om dig",
        "see you soon": "vi ses snart",
        "I'll be right back": "jag kommer strax tillbaka",
        "do you have time?": "har du tid?",
        "what do you think?": "vad tycker du?",
        "how can I help?": "hur kan jag hjälpa till?",
        "is everything okay?": "är allt okej?",
        "I'm ready": "jag är redo",
        "I'm not ready": "jag är inte redo",
        "I forgot": "jag glömde",
        "I remember": "jag kommer ihåg",
        "what's happening?": "vad händer?",
        "I don't feel well": "jag mår inte bra",
        "what do you mean?": "vad menar du?",
        "that's true": "det är sant",
        "that's false": "det är falskt",
        "no worries": "ingen fara",
        "never mind": "strunta i det",
        "that's enough": "det räcker",
        "I'm serious": "jag är allvarlig",
        "are you sure?": "är du säker?",
        "it's not important": "det är inte viktigt",
        "let's wait": "låt oss vänta",
        "don't worry": "oroa dig inte",
        "you're right": "du har rätt",
        "you're wrong": "du har fel",
        "that sounds good": "det låter bra",
        "that sounds bad": "det låter dåligt",
        "it's okay": "det är okej",
        "I don't care": "jag bryr mig inte",
        "I'll try my best": "jag ska göra mitt bästa",
        "I believe in you": "jag tror på dig",
        "it's complicated": "det är komplicerat",
        "I'm surprised": "jag är förvånad",
        "that's not fair": "det är inte rättvist",
        "I appreciate it": "jag uppskattar det",
        "it doesn't matter": "det spelar ingen roll",
        "just kidding": "bara skojar",
        "I need a break": "jag behöver en paus",
        "take it easy": "ta det lugnt",
        "you're awesome": "du är fantastisk",
        "it's your turn": "det är din tur",
        "be careful": "var försiktig",
        "that's weird": "det är konstigt",
        "don't forget": "glöm inte",
        "please be quiet": "var vänlig tyst",
        "watch out": "se upp",
        "it's up to you": "det är upp till dig",
        "I'm proud of you": "jag är stolt över dig",
        "that's impressive": "det är imponerande",
        "let's go home": "låt oss gå hem",
        "have a seat": "varsågod och sitt",
        "may I come in?": "får jag komma in?",
        "are you hungry?": "är du hungrig?",
        "are you thirsty?": "är du törstig?",
        "what's for dinner?": "vad blir det till middag?",
        "don't be shy": "var inte blyg",
        "I'll be there soon": "jag kommer snart",
        "let's celebrate": "låt oss fira",
        "that's surprising": "det är överraskande",
        "I'm feeling lucky": "jag känner mig lycklig",
        "let's take a walk": "låt oss ta en promenad",
        "who's calling?": "vem ringer?",
        "I have no idea": "jag har ingen aning",
        "I'm on my way": "jag är på väg",
        "that's beautiful": "det är vackert",
        "that's horrible": "det är hemskt",
        "I'll miss you": "jag kommer sakna dig",
        "do you remember?": "kommer du ihåg?",
        "it's a secret": "det är en hemlighet",
  
    },
    "verbs": {
        "to be": "vara",
        "to have": "ha",
        "to do": "göra",
        "to say": "säga",
        "to go": "gå",
        "to come": "komma",
        "to see": "se",
        "to know": "veta",
        "to think": "tänka",
        "to take": "ta",
        "to want": "vilja",
        "to give": "ge",
        "to look": "titta",
        "to use": "använda",
        "to find": "hitta",
        "to tell": "berätta",
        "to ask": "fråga",
        "to work": "arbeta",
        "to seem": "verka",
        "to feel": "känna",
        "to leave": "lämna",
        "to call": "ringa",
        "to try": "försöka",
        "to need": "behöva",
        "to become": "bli",
        "to put": "lägga",
        "to mean": "mena",
        "to keep": "behålla",
        "to let": "låta",
        "to begin": "börja",
        "to help": "hjälpa",
        "to show": "visa",
        "to hear": "höra",
        "to play": "spela",
        "to run": "springa",
        "to move": "flytta",
        "to like": "gilla",
        "to live": "leva",
        "to dwell": "bo",
        "to believe": "tro",
        "to hold": "hålla",
        "to bring": "ta med",
        "to happen": "hända",
        "to write": "skriva",
        "to provide": "förse",
        "to sit": "sitta",
        "to stand": "stå",
        "to lose": "förlora",
        "to pay": "betala",
        "to meet": "möta",
        "to include": "inkludera",
        "to set": "ställa",
        "to eat": "äta",
        "to drink": "dricka",
        "to sleep": "sova",
        "to read": "läsa",
        "to buy": "köpa",
        "to sell": "sälja",
        "to drive": "köra",
        "to walk": "gå (promenera)",
        "to swim": "simma",
        "to fly": "flyga",
        "to wait": "vänta",
        "to send": "skicka",
        "to receive": "ta emot",
        "to open": "öppna",
        "to close": "stänga",
        "to build": "bygga",
        "to break": "bryta",
        "to cut": "skära",
        "to cook": "laga mat",
        "to clean": "städa",
        "to wash": "tvätta",
        "to draw": "rita",
        "to paint": "måla",
        "to dance": "dansa",
        "to sing": "sjunga",
        "to smile": "le",
        "to laugh": "skratta",
        "to cry": "gråta",
        "to shout": "ropa",
        "to kiss": "kyssa",
        "to love": "älska",
        "to hate": "hata",
        "to win": "vinna",
        "to choose": "välja",
        "to follow": "följa",
        "to forget": "glömma",
        "to remember": "minnas",
        "to understand": "förstå",
        "to learn": "lära sig",
        "to teach": "undervisa",
        "to wait for": "vänta på",
        "to hope": "hoppas",
        "to plan": "planera",
        "to decide": "bestämma",
        "to explain": "förklara",
        "to change": "ändra",
        "to win over": "övertyga",
        "to borrow": "låna",
        "to lend": "låna ut",
    }
}